language: cpp


env:
  - QUAN_ROOT="/home/travis/build/kwikius/quan-trunk"  CXX="g++-4.8"	

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - ccache
    - g++-4.8
    - gcc-4.8
    
script: pwd && make




